### ISSUE TITLE
Vulkan is twice as slow as OpenGL

### ISSUE THREAD

**Issue by WaneOshin** [veldrid/veldrid#544]
### Hello everyone. 

I am not that experienced with backends but as far as i know vulkan should have atleast the same FPS as OpenGL but testing out the Demo from here and another Sample from Github and my own project, **OpenGL(or OpenGLES) runs x2 faster than Vulkan backend without changing any code**. 
Examples : Demo 226fps vs 100fps  or  MyProject 4800fps vs 2600fps

Is there any reason to this or any way to so called "Fix" this?
Thanks

**Comment by Redhacker1** [comment]
Are you modifying buffers in any way (say like for instance, changing model matrix?)

**Comment by WaneOshin** [comment]
Yes I Update **View**,**Projection**,Matrices and **InstanceBuffer** (Models info for rendering like height or radius) each frame before **Draw** . 
Why so?

**Comment by Redhacker1** [comment]
If you modify a buffer in the middle of the frame, veldrid has to stall the GPU to end and start a new renderpass, update the buffer and *then* continue drawing commands. That process is slow.

**Comment by Redhacker1** [comment]
Look at renderdoc and see if you can identify. That's what it's doing. What I would suggest doing as a workaround is either storing a buffer per object and updating them before you draw the frame. Or use a large buffer of that data that is traversed per instance. I have an example on how to do this on my Minecraft clone core project, I would recommend taking a look at it.

Veldrid doesn't expose the concept of push constants because opengl I believe doesn't expose them, DirectX 11 might not either. So either one of those is your only option

**Comment by Redhacker1** [comment]
Look at renderdoc and see if you can identify. That's what it's doing. What I would suggest doing as a workaround is either storing a buffer per object and updating them before you draw the frame. Or use a large buffer of that data that is traversed per instance. I have an example on how to do this on my Minecraft clone core project, I would recommend taking a look at it.

Veldrid doesn't expose the concept of push constants because opengl I believe doesn't expose them, DirectX 11 might not either. So either one of those is your only option

**Comment by Redhacker1** [comment]
Do you mind showing me what drawcalls look like in renderdoc?

**Comment by Redhacker1** [comment]
Literally just a screenshot of what renderdoc shows can be immensely helpful

**Comment by WaneOshin** [comment]
Thanks this really helped. I installed RenderDoc and this is a single frame:
![image](https://github.com/user-attachments/assets/a78defb2-e542-40c2-a923-63b12bff9e95)
What am i doing wrong ? i dont understand much...

I Tested NeoDemo again and your right OpenGl does run slower than Vulkan I was testing it on "Debug" (which gives opposite results, my bad)!!!

**Comment by WaneOshin** [comment]
and this is the code in the "Loop":
![image](https://github.com/user-attachments/assets/0aa4dc53-99b4-487c-ba25-7cab1ca9546d)
Each "Draw" has its own **setVertex** and **UpdateBuffer** and **Draw** ...

**Comment by Redhacker1** [comment]
All that begin and end render pass stuff is bad. That being said, I will assume that is immediate mode gui being an issue. 

Focusing on your code. The wait for idle is unnecessary, try removing it

**Comment by Redhacker1** [comment]
You don't want to do any updating of the buffers during your draw loop. In order to update the buffer, veldrid has to end the renderpass and start a new one. That implicitly means that you're essentially calling wait for idle every time you update the buffers.

**Comment by Redhacker1** [comment]
You still having issues?

**Comment by WaneOshin** [comment]
immediate mode gui didnt really affect the fps.
I have to rewrite all the code which takes time and implement what you said (so i update buffers in a separate {cl.begin,...,cl.end}).
**Thanks alot for the help** ,this is probably a more in-depth problem i have to work on but for now i think this issue is over since nobody else has this problem.

**Comment by WaneOshin** [comment]
> You don't want to do any updating of the buffers during your draw loop. In order to update the buffer, veldrid has to end the renderpass and start a new one. That implicitly means that you're essentially calling wait for idle every time you update the buffers. Because the GPU has to finish the current render pass before it can start another.

how am i supposed to update the buffers then? this is how the samples do it!....

**Comment by Redhacker1** [comment]
What you're supposed to do is you're supposed to update all of your buffers before you do any drawing. That being said, why do you really care if you're still getting 4,000 FPS? If Vulkan scales worse than opengl then care.

**Comment by WaneOshin** [comment]
### All the draws I do are _instanced_ and use combined matrices!

yes i update buffers before draws but i have **multiple draws** with **different pipelines** that use the same index buffers with **different data** in those buffers. this is where i have to updateBuffer() between draws and i dont think theres a proper way around it (unless i combine data into a bigger buffer). Imagine this : _DrawInstancedSpheres() -> DrawInstancedBoxes() -> ..._

You're right about scaling and the FPS, i havent tested a BIG scene yet and that might make a difference. I was just questioning why Vulkan was so much slower than OpenGL and you have helped me fix a big part of it still doesnt make sence to me to run , albeit slightly, slower.

**Comment by Redhacker1** [comment]
If you can't do anything to avoid it, then don't use Vulkan.

The Vulkan back end is not set up for Your style of renderer. That's just a fact you're going to have to live with because you have to stall the GPU to update the buffers. That is where your slowdown is coming from. You either need to update the data once before the frame is drawn or accept poor performance. 

Vulkan is not set up for you to be able to update buffers in the middle of a frame. You either need to do it at the beginning or the end or suffer poor performance.

If you already make use of instancing that's one of the tools in your toolbox taken away to work around it, there's not a lot you can do other than just deal with it.
